//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMAP.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingUdpAutoConnect {
            get {
                return ((bool)(this["SettingUdpAutoConnect"]));
            }
            set {
                this["SettingUdpAutoConnect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingJoyAutoConnect {
            get {
                return ((bool)(this["SettingJoyAutoConnect"]));
            }
            set {
                this["SettingJoyAutoConnect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SettingJoyStringConnect {
            get {
                return ((string)(this["SettingJoyStringConnect"]));
            }
            set {
                this["SettingJoyStringConnect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("04001")]
        public string SettingUdpPort {
            get {
                return ((string)(this["SettingUdpPort"]));
            }
            set {
                this["SettingUdpPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.000.000.001:50001")]
        public string SettingAddressMud {
            get {
                return ((string)(this["SettingAddressMud"]));
            }
            set {
                this["SettingAddressMud"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.000.000.001:50002")]
        public string SettingAddressNav {
            get {
                return ((string)(this["SettingAddressNav"]));
            }
            set {
                this["SettingAddressNav"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.100.100:04001")]
        public string SettingAddressPwm1 {
            get {
                return ((string)(this["SettingAddressPwm1"]));
            }
            set {
                this["SettingAddressPwm1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.100.100:04002")]
        public string SettingAddressPwm2 {
            get {
                return ((string)(this["SettingAddressPwm2"]));
            }
            set {
                this["SettingAddressPwm2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.100.100:04003")]
        public string SettingAddressPwm3 {
            get {
                return ((string)(this["SettingAddressPwm3"]));
            }
            set {
                this["SettingAddressPwm3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.100.100:04004")]
        public string SettingAddressEngine {
            get {
                return ((string)(this["SettingAddressEngine"]));
            }
            set {
                this["SettingAddressEngine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.100.101:04005")]
        public string SettingAddressCamera {
            get {
                return ((string)(this["SettingAddressCamera"]));
            }
            set {
                this["SettingAddressCamera"] = value;
            }
        }
    }
}
